

# company_lst_4 = ['MEGHNALIFE',
#  'PAPERPROC',
#  'ZAHINTEX',
#  'STYLECRAFT',
#  'NTLTUBES',
#  'SAMORITA',
#  'CENTRALPHL',
#  'ICBIBANK',
#  'CITYBANK',
#  'ASIAINS',
#  'PUBALIBANK',
#  'ZEALBANGLA',
#  'EXIMBANK',
#  'HRTEX',
#  'PRIMETEX',
#  'STANCERAM',
#  'NCCBANK',
#  'GEMINISEA',
#  'ALLTEX',
#  'ENVOYTEX',
#  'ICBEPMF1S1',
#  'FINEFOODS',
#  'PEOPLESINS',
#  'RELIANCE1',
#  'BDAUTOCA',
#  'BBS',
#  'MERCINS',
#  'NRBCBANK',
#  'EASTLAND',
#  'AZIZPIPES',
#  'RDFOOD',
#  'WALTONHIL',
#  'ACMEPL',
#  'TILIL',
#  'HFL',
#  'DBH1STMF',
#  'WATACHEM',
#  'AMBEEPHA',
#  'BENGALWTL',
#  'AAMRANET',
#  'SAVAREFR',
#  'STANDARINS',
#  'PLFSL',
#  'PRIMEBANK',
#  'SSSTEEL',
#  'ETL',
#  'MONNOAGML',
#  'RELIANCINS',
#  'ILFSL',
#  'NFML',
#  'FUWANGFOOD',
#  'PREMIERBAN',
#  'CONTININS',
#  'DACCADYE',
#  'BARKAPOWER',
#  'BXSYNTH',
#  'DUTCHBANGL',
#  'WMSHIPYARD',
#  'ATCSLGF',
#  'MHSML',
#  'MAKSONSPIN',
#  'CLICL',
#  'PHPMF1',
#  'RECKITTBEN',
#  'GHAIL',
#  'SHASHADNIM',
#  'TALLUSPIN',
#  'COPPERTECH',
#  'ICBAGRANI1',
#  'SHURWID',
#  'MPETROLEUM',
#  'BDLAMPS',
#  'MEGHNACEM',
#  'FUWANGCER',
#  'CVOPRL',
#  'PHENIXINS',
#  'PIONEERINS',
#  'PURABIGEN',
#  'SKICL',
#  'UCB',
#  'AIL',
#  'EASTERNINS',
#  'QUEENSOUTH',
#  'LHBL',
#  'PHOENIXFIN',
#  'NAVANAPHAR',
#  'HAKKANIPUL',
#  'ITC',
#  'ICBAMCL2ND',
#  'MIRACLEIND',
#  'GLDNJMF',
#  'NEWLINE',
#  'ACTIVEFINE',
#  'KPPL',
#  'MONNOCERA',
#  'DELTALIFE',
#  'BNICL',
#  'FAREASTLIF',
#  'APOLOISPAT',
#  'BDWELDING',
#  'ARAMITCEM',
#  'GRAMEENS2',
#  'GREENDELT',
#  'SAIHAMTEX',
#  'RUPALIBANK',
#  'SEMLIBBLSF',
#  'BIFC',
#  'ICBSONALI1',
#  'DAFODILCOM',
#  'SAPORTL',
#  'IFIC',
#  'HEIDELBCEM',
#  'EMERALDOIL',
#  'EIL',
#  'RINGSHINE',
#  'GQBALLPEN',
#  'BDTHAI',
#  'FEKDIL',
#  'UNITEDINS',
#  'TITASGAS',
#  'SONALIANSH',
#  'ACFL',
#  'MLDYEING',
#  'SHYAMPSUG',
#  'ROBI',
#  'SAIHAMCOT',
#  'JHRML',
#  'KAYQUE',
#  'ICB3RDNRB',
#  'TRUSTB1MF',
#  'RSRMSTEEL',
#  'GREENDELMF',
#  'MEGHNAINS',
#  'PRIMEINSUR',
#  'DHAKAINS',
#  'SUNLIFEINS',
#  'CAPMIBBLMF',
#  'CNATEX',
#  'BATASHOE',
#  'LRBDL',
#  'UNILEVERCL',
#  'TAKAFULINS',
#  'PDL',
#  'MONOSPOOL',
#  'SONARBAINS',
#  'JAMUNABANK',
#  'NCCBLMF1',
#  'DSHGARME',
#  'IBP',
#  'SONALIPAPR',
#  'MALEKSPIN',
#  'GIB',
#  'BEXIMCO',
#  'EASTRNLUB',
#  'NITOLINS',
#  'SOUTHEASTB',
#  'FASFIN',
#  'PADMALIFE',
#  'GHCL',
#  'CAPMBDBLMF',
#  'AFCAGRO',
#  'SUMITPOWER',
#  'APEXTANRY',
#  'ICICL',
#  'ISLAMICFIN',
#  'SANDHANINS',
#  'BSRMLTD',
#  'OIMEX',
#  'DSSL',
#  'IFIC1STMF',
#  'UNIONCAP',
#  'EGEN',
#  'EBL',
#  'IFADAUTOS',
#  'LRGLOBMF1',
#  'INDEXAGRO',
#  'IBNSINA',
#  'BEACHHATCH',
#  'DESHBANDHU',
#  'MEGCONMILK',
#  'ALIF',
#  'MERCANBANK',
#  'GP',
#  'IMAMBUTTON',
#  'BPML',
#  'CRYSTALINS',
#  'DGIC',
#  'FBFIF',
#  'VAMLBDMF1',
#  'DOMINAGE',
#  'ICB',
#  'DESCO',
#  'IFILISLMF1',
#  'SINGERBD',
#  'FAMILYTEX',
#  'RUPALILIFE',
#  'ONEBANKLTD',
#  'FIRSTSBANK',
#  'BPPL',
#  'MBL1STMF',
#  'SAFKOSPINN',
#  'QUASEMIND',
#  'BDTHAIFOOD',
#  'NLI1STMF',
#  'AIBL1STIMF',
#  'DBH',
#  'SILCOPHL',
#  'CENTRALINS',
#  'RAKCERAMIC',
#  'POPULARLIF',
#  'NHFIL',
#  'KEYACOSMET',
#  'AAMRATECH',
#  'ESQUIRENIT',
#  'SBACBANK',
#  'INTECH',
#  'PRAGATIINS',
#  'MTB',
#  'BSRMSTEEL',
#  'ADNTEL',
#  'ECABLES',
#  'RAHIMTEXT',
#  'SAIFPOWER',
#  'LEGACYFOOT',
#  'AMANFEED',
#  'GOLDENSON',
#  'FEDERALINS',
#  'SEMLLECMF',
#  'METROSPIN',
#  'NURANI',
#  'UTTARAFIN',
#  'ORIONINFU',
#  'AOL',
#  'GBBPOWER',
#  'NATLIFEINS',
#  'PROGRESLIF',
#  'YPL',
#  'ORIONPHARM',
#  'TAMIJTEX',
#  'PF1STMF',
#  'SEMLFBSLGF',
#  'ADVENT',
#  'FIRSTFIN',
#  'AFTABAUTO',
#  'MIDASFIN',
#  'SKTRIMS',
#  'NORTHERN',
#  'ALHAJTEX',
#  'ANLIMAYARN',
#  'JMISMDL',
#  'EXIM1STMF',
#  'SIMTEX',
#  'MIDLANDBNK',
#  'RUPALIINS',
#  'PTL',
#  'GLOBALINS',
#  'USMANIAGL',
#  'PADMAOIL',
#  'LANKABAFIN',
#  'NAHEEACP',
#  'RNSPIN',
#  'KDSALTD',
#  'AMCLPRAN',
#  'KOHINOOR',
#  'ALARABANK',
#  'DHAKABANK',
#  'MEGHNAPET',
#  'BDFINANCE',
#  'RANFOUNDRY',
#  'TOSRIFA',
#  'BDSERVICE',
#  'UTTARABANK',
#  '1JANATAMF',
#  'PENINSULA',
#  'PREMIERLEA',
#  'SPCERAMICS',
#  'DULAMIACOT',
#  'APEXSPINN',
#  'DELTASPINN',
#  'KTL',
#  'REGENTTEX',
#  'EBLNRBMF',
#  'BXPHARMA',
#  'ISLAMIBANK',
#  'EPGL',
#  'STANDBANKL',
#  'ASIAPACINS',
#  'MONNOFABR',
#  'VAMLRBBF',
#  'NORTHRNINS',
#  'SINOBANGLA',
#  'UNIONBANK',
#  'TUNGHAI',
#  'FAREASTFIN',
#  'EBL1STMF',
#  'REPUBLIC',
#  'ABBANK',
#  'ISLAMIINS',
#  'BANKASIA',
#  'PRAGATILIF',
#  'PRIME1ICBA',
#  'PRIMEFIN',
#  'SHAHJABANK',
#  'BAYLEASING',
#  'PROVATIINS',
#  'BRACBANK',
#  'AGNISYSL',
#  'OAL',
#  'SALAMCRST',
#  'UNITEDFIN',
#  'UNIQUEHRL',
#  'SIBL',
#  'ABB1STMF',
#  'SILVAPHL',
#  'MIRAKHTER',
#  'ZAHEENSPIN',
#  'RENWICKJA',
#  'UNIONINS',
#  'JUTESPINN',
#  'ISNLTD',
#  'POPULAR1MF',
#  'PRIMELIFE',
#  'SONALILIFE',
#  'AGRANINS',
#  'KBPPWBIL',
#  'NBL',
#  'VFSTDL',
#  'SEAPEARL',
#  'BBSCABLES',
#  'MITHUNKNIT',
#  'GENNEXT',
#  'JANATAINS',
#  'BGIC',
#  'CONFIDCEM',
#  'PREMIERCEM',
#  'SAMATALETH',
#  'SONARGAON',
#  'NTC',
#  'RUNNERAUTO',
#  'LIBRAINFU',
#  'BANGAS',
#  'KARNAPHULI',
#  'APEXFOOT',
#  'SHEPHERD',
#  'NAVANACNG',
#  'ATLASBANG',
#  'ARGONDENIM',
#  'FARCHEM',
#  'BEACONPHAR',
#  '1STPRIMFMF',
#  'CROWNCEMNT',
#  'LOVELLO',
#  'GENEXIL',
#  'CITYGENINS']


# company_lst = company_lst # + company_lst_4 #+ company_lst_3
# + company_lst_2 



# company_symbol_lst = [                   
#                      'd',
#                      'd',
#                      'd',
#                      'd',
    
#                      'd',
#                      'd',
#                      'd',
#                      'd',

#                      'd',
#                      'd',
#                      'd',
#                      #################
#                      'd+',
#                      'd+',
#                      'd+',
#                      'd+',

#                      'd+',
#                      'd+',
#                      'd+',
#                      'd+',

#                      'd+',
#                      'd+',
#                      'd+',
#                      'd+',

#                      'd+',
#                      'd+',
#                      'd+',
#                      'd+',
#                      #################
#                      't',
#                      't',
#                      't',
#                      't',
    
#                      't',
#                      #################
#                      'c',
#                      'c',
#                      'c',
#                      'c',

#                      'c',
#                      'c',
#                      'c',
#                      'c',

#                      'c',
#                      'c',
#                      'c',
#                     #################
#                      ]


# new_symb = ['c+']*len(company_lst_2)
# new_symb_2 = ['c+']*len(company_lst_3)
# new_symb_3 = ['c+']*len(company_lst_4)

company_lst_3 = [
    'RELIANCE1',
 'BDAUTOCA',
 'BBS',
 'MERCINS',
 'NRBCBANK',
 'EASTLAND',
 'AZIZPIPES',
 'RDFOOD',
 'WALTONHIL',
 'ACMEPL',
 'TILIL',
 'HFL',
 'DBH1STMF',
 'WATACHEM',
 'AMBEEPHA',
 'BENGALWTL',
 'AAMRANET',
 'SAVAREFR',
 'STANDARINS',
 'PLFSL',
 'PRIMEBANK',
 'SSSTEEL',
 'ETL',
 'MONNOAGML',
 'RELIANCINS',
 'ILFSL',
 'NFML',
 'FUWANGFOOD',
 'PREMIERBAN',
 'CONTININS',
 'DACCADYE',
 'BARKAPOWER',
 'BXSYNTH',
 'DUTCHBANGL',
 'WMSHIPYARD',
 'ATCSLGF',
 'MHSML',
 'MAKSONSPIN',
 'CLICL',
 'PHPMF1',
 'RECKITTBEN',
 'GHAIL',
 'SHASHADNIM',
 'TALLUSPIN',
 'COPPERTECH',
 'ICBAGRANI1',
 'SHURWID',
 'MPETROLEUM',
 'BDLAMPS',
 'MEGHNACEM',
 'FUWANGCER',
 'CVOPRL',
 'PHENIXINS',
 'PIONEERINS',
 'PURABIGEN',
 'SKICL',
 'UCB',
 'AIL',
 'EASTERNINS',
 'QUEENSOUTH',
 'LHBL',
 'PHOENIXFIN',
 'NAVANAPHAR',
 'HAKKANIPUL',
 'ITC',
 'ICBAMCL2ND',
 'MIRACLEIND',
 'GLDNJMF',
 'NEWLINE',
 'ACTIVEFINE',
 'KPPL',
 'MONNOCERA',
 'DELTALIFE',
 'BNICL',
 'FAREASTLIF',
 'APOLOISPAT',
 'BDWELDING',
 'ARAMITCEM',
 'GRAMEENS2',
 'GREENDELT',
 'SAIHAMTEX',
 'RUPALIBANK',
 'SEMLIBBLSF',
 'BIFC',
 'ICBSONALI1',
 'DAFODILCOM',
 'SAPORTL',
 'IFIC',
 'HEIDELBCEM',
 'EMERALDOIL',
 'EIL',
 'RINGSHINE',
 'GQBALLPEN',
 'BDTHAI',
 'FEKDIL',
 'UNITEDINS',
 'TITASGAS',
 'SONALIANSH',
 'ACFL',
 'MLDYEING',
 'SHYAMPSUG',
 'ROBI',
 'SAIHAMCOT',
 'JHRML',
 'KAYQUE',
 'ICB3RDNRB',
 'TRUSTB1MF',
 'RSRMSTEEL',
 'GREENDELMF',
 'MEGHNAINS',
 'PRIMEINSUR',
 'DHAKAINS',
 'SUNLIFEINS',
 'CAPMIBBLMF',
 'CNATEX',
 'BATASHOE',
 'LRBDL',
 'UNILEVERCL',
 'TAKAFULINS',
 'PDL',
 'MONOSPOOL',
 'SONARBAINS',
 'JAMUNABANK',
 'NCCBLMF1',
 'DSHGARME',
 'IBP',
]
company_lst = company_lst_3

count = len(company_lst_3) 
company_lst_3_symb = ['c+']*count
company_symbol_lst = company_lst_3_symb # + new_symb_3  # + new_symb_2
# + new_symb 

